{
 "title": "application-metrics",
 "time": { "from": "now-3h", "to": "now" },
 "panels": [
  {
   "title": "RPS_all_users",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (all_users_seconds_count) (rate(all_users_seconds_count[2m]))",
     "legendFormat": "rps"
    }
   ]
  },
  {
   "title": "RPS_user_by_email",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (user_by_email_seconds_count) (rate(user_by_email_seconds_count[2m]))",
     "legendFormat": "rps"
    }
   ]
  },
  {
   "title": "Quantile_all_users",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (quantile) (all_users_seconds)"
    }
   ]
  },
  {
   "title": "Quantile_user_by_email",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (quantile) (user_by_email_seconds)"
    }
   ]
  },
  {
   "title": "ERROR_RATE_all_users",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 18 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "all_users_seconds_count{status=\"500\"}"
    }
   ]
  },
  {
   "title": "ERROR_RATE_user_by_email",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 18 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum by (user_by_email_seconds_count) (user_by_email_seconds_count{status=\"500\"})"
    }
   ]
  },
  {
   "title": "jvm_memory_used_bytes",
   "type": "graph",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 26 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "sum by (jvm_memory_used_bytes) (jvm_memory_used_bytes{area=\"heap\"})"
    }
   ]
  },
  {
   "title": "Кол-во запросов через ingress-nginx-controller",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 36 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "nginx_ingress_controller_nginx_process_requests_total"
    }
   ]
  }
 ]
}